"""verification fields added to user

Revision ID: 149a3cf2993f
Revises: fe6b9fce03ff
Create Date: 2026-03-12 19:55:30.846850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149a3cf2993f'
down_revision = 'fe6b9fce03ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_verified')
        batch_op.drop_column('verification_token')

    # ### end Alembic commands ###
