"""user table email necessary

Revision ID: 384906aa66d1
Revises: a4fbe12441c7
Create Date: 2026-03-07 21:41:21.357083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '384906aa66d1'
down_revision = 'a4fbe12441c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###
